// Package geometry provides explicitly selectable, source-key-verified editor
// layouts. A device's display name is never used to choose a layout.

// Code generated from kmonad's src/KMonad/Keyboard/Keycode.hs at commit
// 30b9705fb56059483969624d58cad077d5c62300 by scripts/generate-kmonad-vocabulary.py. DO NOT EDIT.
// Regenerate from the repository root:
//   python3 scripts/generate-kmonad-vocabulary.py internal/geometry/kmonad_vocabulary.go
// The vocabulary tests pin this table to that commit's source counts.
//
// The table is the verified KMonad keyboard-token vocabulary: every Key*
// keycode constructor that exists at the pinned commit, with the alias
// spellings KMonad accepts. Btn*, Missing*, and VK* ranges are excluded
// because they are not mappable keyboard keys. KMonad accepts, for each
// constructor: the constructor name, its lowercased form, the name with the
// "Key" prefix dropped, that lowercased, and the aliases listed below.

package geometry

import "strings"

// kmonadKeycode is one mappable KMonad keycode at the pinned commit with the
// additional alias spellings KMonad accepts for it.
type kmonadKeycode struct {
	Constructor string
	Aliases     []string
}

// kmonadKeycodes lists every mappable keyboard keycode at the pinned commit.
var kmonadKeycodes = []kmonadKeycode{
	{Constructor: "Key0", Aliases: []string{}},
	{Constructor: "Key1", Aliases: []string{}},
	{Constructor: "Key102nd", Aliases: []string{"102d", "lsgt", "nubs"}},
	{Constructor: "Key10channelsDown", Aliases: []string{}},
	{Constructor: "Key10channelsUp", Aliases: []string{}},
	{Constructor: "Key2", Aliases: []string{}},
	{Constructor: "Key3", Aliases: []string{}},
	{Constructor: "Key3dMode", Aliases: []string{}},
	{Constructor: "Key4", Aliases: []string{}},
	{Constructor: "Key5", Aliases: []string{}},
	{Constructor: "Key6", Aliases: []string{}},
	{Constructor: "Key7", Aliases: []string{}},
	{Constructor: "Key8", Aliases: []string{}},
	{Constructor: "Key9", Aliases: []string{}},
	{Constructor: "KeyA", Aliases: []string{}},
	{Constructor: "KeyAb", Aliases: []string{}},
	{Constructor: "KeyAccessibility", Aliases: []string{}},
	{Constructor: "KeyAddressBook", Aliases: []string{"contacts"}},
	{Constructor: "KeyAgain", Aliases: []string{}},
	{Constructor: "KeyAlsToggle", Aliases: []string{}},
	{Constructor: "KeyAlterase", Aliases: []string{}},
	{Constructor: "KeyAngle", Aliases: []string{}},
	{Constructor: "KeyApostrophe", Aliases: []string{"apos", "'", "apo"}},
	{Constructor: "KeyAppSelect", Aliases: []string{}},
	{Constructor: "KeyArchive", Aliases: []string{}},
	{Constructor: "KeyAssistant", Aliases: []string{}},
	{Constructor: "KeyAttendantOff", Aliases: []string{}},
	{Constructor: "KeyAttendantOn", Aliases: []string{}},
	{Constructor: "KeyAttendantToggle", Aliases: []string{}},
	{Constructor: "KeyAudio", Aliases: []string{}},
	{Constructor: "KeyAudioDesc", Aliases: []string{}},
	{Constructor: "KeyAutopilotEngageToggle", Aliases: []string{}},
	{Constructor: "KeyAux", Aliases: []string{}},
	{Constructor: "KeyB", Aliases: []string{}},
	{Constructor: "KeyBack", Aliases: []string{}},
	{Constructor: "KeyBackslash", Aliases: []string{"bksl", "\\", "nonuspound"}},
	{Constructor: "KeyBackspace", Aliases: []string{"bks", "bspc"}},
	{Constructor: "KeyBassBoost", Aliases: []string{}},
	{Constructor: "KeyBattery", Aliases: []string{}},
	{Constructor: "KeyBlue", Aliases: []string{}},
	{Constructor: "KeyBluetooth", Aliases: []string{}},
	{Constructor: "KeyBookmarks", Aliases: []string{}},
	{Constructor: "KeyBreak", Aliases: []string{}},
	{Constructor: "KeyBrightnessCycle", Aliases: []string{}},
	{Constructor: "KeyBrightnessDown", Aliases: []string{"brdown", "brdwn", "brdn"}},
	{Constructor: "KeyBrightnessMax", Aliases: []string{}},
	{Constructor: "KeyBrightnessMenu", Aliases: []string{}},
	{Constructor: "KeyBrightnessMin", Aliases: []string{}},
	{Constructor: "KeyBrightnessToggle", Aliases: []string{"displaytoggle"}},
	{Constructor: "KeyBrightnessUp", Aliases: []string{"brup", "bru"}},
	{Constructor: "KeyBrightnessZero", Aliases: []string{"brightnessauto"}},
	{Constructor: "KeyBrlDot1", Aliases: []string{}},
	{Constructor: "KeyBrlDot10", Aliases: []string{}},
	{Constructor: "KeyBrlDot2", Aliases: []string{}},
	{Constructor: "KeyBrlDot3", Aliases: []string{}},
	{Constructor: "KeyBrlDot4", Aliases: []string{}},
	{Constructor: "KeyBrlDot5", Aliases: []string{}},
	{Constructor: "KeyBrlDot6", Aliases: []string{}},
	{Constructor: "KeyBrlDot7", Aliases: []string{}},
	{Constructor: "KeyBrlDot8", Aliases: []string{}},
	{Constructor: "KeyBrlDot9", Aliases: []string{}},
	{Constructor: "KeyButtonconfig", Aliases: []string{}},
	{Constructor: "KeyC", Aliases: []string{}},
	{Constructor: "KeyCalc", Aliases: []string{"calculator"}},
	{Constructor: "KeyCalendar", Aliases: []string{"schedule"}},
	{Constructor: "KeyCamera", Aliases: []string{}},
	{Constructor: "KeyCameraAccessDisable", Aliases: []string{}},
	{Constructor: "KeyCameraAccessEnable", Aliases: []string{}},
	{Constructor: "KeyCameraAccessToggle", Aliases: []string{}},
	{Constructor: "KeyCameraDown", Aliases: []string{}},
	{Constructor: "KeyCameraFocus", Aliases: []string{}},
	{Constructor: "KeyCameraLeft", Aliases: []string{}},
	{Constructor: "KeyCameraRight", Aliases: []string{}},
	{Constructor: "KeyCameraUp", Aliases: []string{}},
	{Constructor: "KeyCameraZoomIn", Aliases: []string{}},
	{Constructor: "KeyCameraZoomOut", Aliases: []string{}},
	{Constructor: "KeyCancel", Aliases: []string{}},
	{Constructor: "KeyCapsLock", Aliases: []string{"caps"}},
	{Constructor: "KeyCd", Aliases: []string{}},
	{Constructor: "KeyChannel", Aliases: []string{}},
	{Constructor: "KeyChannelDown", Aliases: []string{}},
	{Constructor: "KeyChannelUp", Aliases: []string{}},
	{Constructor: "KeyChat", Aliases: []string{}},
	{Constructor: "KeyClear", Aliases: []string{}},
	{Constructor: "KeyClearvuSonar", Aliases: []string{}},
	{Constructor: "KeyClose", Aliases: []string{}},
	{Constructor: "KeyCloseCd", Aliases: []string{}},
	{Constructor: "KeyCoffee", Aliases: []string{"lock", "screenlock", "termlock"}},
	{Constructor: "KeyComma", Aliases: []string{"comm", ","}},
	{Constructor: "KeyCompose", Aliases: []string{"comp", "cmps", "cmp", "app", "application"}},
	{Constructor: "KeyComputer", Aliases: []string{}},
	{Constructor: "KeyConfig", Aliases: []string{}},
	{Constructor: "KeyConnect", Aliases: []string{}},
	{Constructor: "KeyContextMenu", Aliases: []string{}},
	{Constructor: "KeyControlPanel", Aliases: []string{}},
	{Constructor: "KeyCopy", Aliases: []string{}},
	{Constructor: "KeyCut", Aliases: []string{}},
	{Constructor: "KeyCycleWindows", Aliases: []string{}},
	{Constructor: "KeyD", Aliases: []string{}},
	{Constructor: "KeyDashboard", Aliases: []string{"allapplications"}},
	{Constructor: "KeyData", Aliases: []string{}},
	{Constructor: "KeyDatabase", Aliases: []string{}},
	{Constructor: "KeyDelEol", Aliases: []string{}},
	{Constructor: "KeyDelEos", Aliases: []string{}},
	{Constructor: "KeyDelLine", Aliases: []string{}},
	{Constructor: "KeyDelete", Aliases: []string{"del"}},
	{Constructor: "KeyDeleteFile", Aliases: []string{}},
	{Constructor: "KeyDictate", Aliases: []string{}},
	{Constructor: "KeyDictation", Aliases: []string{"dict"}},
	{Constructor: "KeyDigits", Aliases: []string{}},
	{Constructor: "KeyDirection", Aliases: []string{"rotatedisplay"}},
	{Constructor: "KeyDirectory", Aliases: []string{}},
	{Constructor: "KeyDisplayOff", Aliases: []string{}},
	{Constructor: "KeyDoNotDisturb", Aliases: []string{"dnd"}},
	{Constructor: "KeyDocuments", Aliases: []string{}},
	{Constructor: "KeyDollar", Aliases: []string{}},
	{Constructor: "KeyDot", Aliases: []string{"."}},
	{Constructor: "KeyDown", Aliases: []string{}},
	{Constructor: "KeyDualRangeRadar", Aliases: []string{}},
	{Constructor: "KeyDvd", Aliases: []string{}},
	{Constructor: "KeyE", Aliases: []string{}},
	{Constructor: "KeyEdit", Aliases: []string{}},
	{Constructor: "KeyEditor", Aliases: []string{"texteditor"}},
	{Constructor: "KeyEjectCd", Aliases: []string{"eject"}},
	{Constructor: "KeyEjectCloseCd", Aliases: []string{}},
	{Constructor: "KeyEmail", Aliases: []string{}},
	{Constructor: "KeyEmojiPicker", Aliases: []string{}},
	{Constructor: "KeyEnd", Aliases: []string{}},
	{Constructor: "KeyEnter", Aliases: []string{"ret", "return", "ent"}},
	{Constructor: "KeyEpg", Aliases: []string{}},
	{Constructor: "KeyEqual", Aliases: []string{"eql", "="}},
	{Constructor: "KeyEsc", Aliases: []string{}},
	{Constructor: "KeyEuro", Aliases: []string{}},
	{Constructor: "KeyExit", Aliases: []string{"quit"}},
	{Constructor: "KeyF", Aliases: []string{}},
	{Constructor: "KeyF1", Aliases: []string{}},
	{Constructor: "KeyF10", Aliases: []string{}},
	{Constructor: "KeyF11", Aliases: []string{}},
	{Constructor: "KeyF12", Aliases: []string{}},
	{Constructor: "KeyF13", Aliases: []string{}},
	{Constructor: "KeyF14", Aliases: []string{}},
	{Constructor: "KeyF15", Aliases: []string{}},
	{Constructor: "KeyF16", Aliases: []string{}},
	{Constructor: "KeyF17", Aliases: []string{}},
	{Constructor: "KeyF18", Aliases: []string{}},
	{Constructor: "KeyF19", Aliases: []string{}},
	{Constructor: "KeyF2", Aliases: []string{}},
	{Constructor: "KeyF20", Aliases: []string{}},
	{Constructor: "KeyF21", Aliases: []string{}},
	{Constructor: "KeyF22", Aliases: []string{}},
	{Constructor: "KeyF23", Aliases: []string{}},
	{Constructor: "KeyF24", Aliases: []string{}},
	{Constructor: "KeyF3", Aliases: []string{}},
	{Constructor: "KeyF4", Aliases: []string{}},
	{Constructor: "KeyF5", Aliases: []string{}},
	{Constructor: "KeyF6", Aliases: []string{}},
	{Constructor: "KeyF7", Aliases: []string{}},
	{Constructor: "KeyF8", Aliases: []string{}},
	{Constructor: "KeyF9", Aliases: []string{}},
	{Constructor: "KeyFastForward", Aliases: []string{}},
	{Constructor: "KeyFastreverse", Aliases: []string{}},
	{Constructor: "KeyFavorites", Aliases: []string{}},
	{Constructor: "KeyFile", Aliases: []string{"localmachinebrowser"}},
	{Constructor: "KeyFinance", Aliases: []string{"checkbook"}},
	{Constructor: "KeyFind", Aliases: []string{}},
	{Constructor: "KeyFirst", Aliases: []string{}},
	{Constructor: "KeyFishingChart", Aliases: []string{}},
	{Constructor: "KeyFn", Aliases: []string{}},
	{Constructor: "KeyFn1", Aliases: []string{}},
	{Constructor: "KeyFn2", Aliases: []string{}},
	{Constructor: "KeyFnB", Aliases: []string{}},
	{Constructor: "KeyFnD", Aliases: []string{}},
	{Constructor: "KeyFnE", Aliases: []string{}},
	{Constructor: "KeyFnEsc", Aliases: []string{}},
	{Constructor: "KeyFnF", Aliases: []string{}},
	{Constructor: "KeyFnF1", Aliases: []string{}},
	{Constructor: "KeyFnF10", Aliases: []string{}},
	{Constructor: "KeyFnF11", Aliases: []string{}},
	{Constructor: "KeyFnF12", Aliases: []string{}},
	{Constructor: "KeyFnF2", Aliases: []string{}},
	{Constructor: "KeyFnF3", Aliases: []string{}},
	{Constructor: "KeyFnF4", Aliases: []string{}},
	{Constructor: "KeyFnF5", Aliases: []string{}},
	{Constructor: "KeyFnF6", Aliases: []string{}},
	{Constructor: "KeyFnF7", Aliases: []string{}},
	{Constructor: "KeyFnF8", Aliases: []string{}},
	{Constructor: "KeyFnF9", Aliases: []string{}},
	{Constructor: "KeyFnRightShift", Aliases: []string{}},
	{Constructor: "KeyFnS", Aliases: []string{}},
	{Constructor: "KeyForward", Aliases: []string{"fwd"}},
	{Constructor: "KeyForwardMail", Aliases: []string{"forwardmessage"}},
	{Constructor: "KeyFrameBack", Aliases: []string{}},
	{Constructor: "KeyFrameForward", Aliases: []string{}},
	{Constructor: "KeyFront", Aliases: []string{}},
	{Constructor: "KeyG", Aliases: []string{}},
	{Constructor: "KeyGames", Aliases: []string{}},
	{Constructor: "KeyGoTo", Aliases: []string{}},
	{Constructor: "KeyGraphicsEditor", Aliases: []string{}},
	{Constructor: "KeyGrave", Aliases: []string{"grv", "`"}},
	{Constructor: "KeyGreen", Aliases: []string{}},
	{Constructor: "KeyH", Aliases: []string{}},
	{Constructor: "KeyHangeul", Aliases: []string{"hanguel", "l1", "lang1"}},
	{Constructor: "KeyHangupPhone", Aliases: []string{}},
	{Constructor: "KeyHanja", Aliases: []string{"l2", "lang2"}},
	{Constructor: "KeyHelp", Aliases: []string{"helpcenter"}},
	{Constructor: "KeyHenkan", Aliases: []string{"hen", "i4", "int4", "international4"}},
	{Constructor: "KeyHiragana", Aliases: []string{"l4", "lang4"}},
	{Constructor: "KeyHome", Aliases: []string{}},
	{Constructor: "KeyHomepage", Aliases: []string{}},
	{Constructor: "KeyHp", Aliases: []string{}},
	{Constructor: "KeyI", Aliases: []string{}},
	{Constructor: "KeyImages", Aliases: []string{}},
	{Constructor: "KeyInfo", Aliases: []string{"featurebrowser", "tipsbrowser"}},
	{Constructor: "KeyInsLine", Aliases: []string{}},
	{Constructor: "KeyInsert", Aliases: []string{"ins"}},
	{Constructor: "KeyIso", Aliases: []string{}},
	{Constructor: "KeyJ", Aliases: []string{}},
	{Constructor: "KeyJournal", Aliases: []string{}},
	{Constructor: "KeyK", Aliases: []string{}},
	{Constructor: "KeyKatakana", Aliases: []string{"l3", "lang3"}},
	{Constructor: "KeyKatakanaHiragana", Aliases: []string{"kah", "i2", "int2", "international2"}},
	{Constructor: "KeyKbdIllumDown", Aliases: []string{"bldn"}},
	{Constructor: "KeyKbdIllumToggle", Aliases: []string{}},
	{Constructor: "KeyKbdIllumUp", Aliases: []string{"blup"}},
	{Constructor: "KeyKbdInputAssistAccept", Aliases: []string{}},
	{Constructor: "KeyKbdInputAssistCancel", Aliases: []string{}},
	{Constructor: "KeyKbdInputAssistNext", Aliases: []string{}},
	{Constructor: "KeyKbdInputAssistNextgroup", Aliases: []string{}},
	{Constructor: "KeyKbdInputAssistPrev", Aliases: []string{}},
	{Constructor: "KeyKbdInputAssistPrevgroup", Aliases: []string{}},
	{Constructor: "KeyKbdLayoutNext", Aliases: []string{}},
	{Constructor: "KeyKbdLcdMenu1", Aliases: []string{}},
	{Constructor: "KeyKbdLcdMenu2", Aliases: []string{}},
	{Constructor: "KeyKbdLcdMenu3", Aliases: []string{}},
	{Constructor: "KeyKbdLcdMenu4", Aliases: []string{}},
	{Constructor: "KeyKbdLcdMenu5", Aliases: []string{}},
	{Constructor: "KeyKeyboard", Aliases: []string{}},
	{Constructor: "KeyKp0", Aliases: []string{}},
	{Constructor: "KeyKp1", Aliases: []string{}},
	{Constructor: "KeyKp2", Aliases: []string{}},
	{Constructor: "KeyKp3", Aliases: []string{}},
	{Constructor: "KeyKp4", Aliases: []string{}},
	{Constructor: "KeyKp5", Aliases: []string{}},
	{Constructor: "KeyKp6", Aliases: []string{}},
	{Constructor: "KeyKp7", Aliases: []string{}},
	{Constructor: "KeyKp8", Aliases: []string{}},
	{Constructor: "KeyKp9", Aliases: []string{}},
	{Constructor: "KeyKpAsterisk", Aliases: []string{"kp*"}},
	{Constructor: "KeyKpComma", Aliases: []string{}},
	{Constructor: "KeyKpDot", Aliases: []string{"kp."}},
	{Constructor: "KeyKpEnter", Aliases: []string{"kprt"}},
	{Constructor: "KeyKpEqual", Aliases: []string{}},
	{Constructor: "KeyKpLeftParen", Aliases: []string{}},
	{Constructor: "KeyKpMinus", Aliases: []string{"kp-"}},
	{Constructor: "KeyKpPlus", Aliases: []string{"kp+"}},
	{Constructor: "KeyKpPlusMinus", Aliases: []string{}},
	{Constructor: "KeyKpRightParen", Aliases: []string{}},
	{Constructor: "KeyKpSlash", Aliases: []string{"kp/"}},
	{Constructor: "KeyKpjpcomma", Aliases: []string{"i6", "int6", "international6"}},
	{Constructor: "KeyL", Aliases: []string{}},
	{Constructor: "KeyLanguage", Aliases: []string{}},
	{Constructor: "KeyLast", Aliases: []string{}},
	{Constructor: "KeyLaunchpad", Aliases: []string{"lp"}},
	{Constructor: "KeyLeft", Aliases: []string{"lft"}},
	{Constructor: "KeyLeftAlt", Aliases: []string{"lalt", "alt"}},
	{Constructor: "KeyLeftBrace", Aliases: []string{"lbrc", "["}},
	{Constructor: "KeyLeftCtrl", Aliases: []string{"lctrl", "lctl", "ctl"}},
	{Constructor: "KeyLeftDown", Aliases: []string{}},
	{Constructor: "KeyLeftMeta", Aliases: []string{"lmeta", "lmet", "met"}},
	{Constructor: "KeyLeftShift", Aliases: []string{"lshift", "lshft", "lsft", "shft", "sft"}},
	{Constructor: "KeyLeftUp", Aliases: []string{}},
	{Constructor: "KeyLightsToggle", Aliases: []string{}},
	{Constructor: "KeyLinefeed", Aliases: []string{}},
	{Constructor: "KeyList", Aliases: []string{}},
	{Constructor: "KeyLogoff", Aliases: []string{}},
	{Constructor: "KeyM", Aliases: []string{}},
	{Constructor: "KeyMacro", Aliases: []string{}},
	{Constructor: "KeyMacro1", Aliases: []string{}},
	{Constructor: "KeyMacro10", Aliases: []string{}},
	{Constructor: "KeyMacro11", Aliases: []string{}},
	{Constructor: "KeyMacro12", Aliases: []string{}},
	{Constructor: "KeyMacro13", Aliases: []string{}},
	{Constructor: "KeyMacro14", Aliases: []string{}},
	{Constructor: "KeyMacro15", Aliases: []string{}},
	{Constructor: "KeyMacro16", Aliases: []string{}},
	{Constructor: "KeyMacro17", Aliases: []string{}},
	{Constructor: "KeyMacro18", Aliases: []string{}},
	{Constructor: "KeyMacro19", Aliases: []string{}},
	{Constructor: "KeyMacro2", Aliases: []string{}},
	{Constructor: "KeyMacro20", Aliases: []string{}},
	{Constructor: "KeyMacro21", Aliases: []string{}},
	{Constructor: "KeyMacro22", Aliases: []string{}},
	{Constructor: "KeyMacro23", Aliases: []string{}},
	{Constructor: "KeyMacro24", Aliases: []string{}},
	{Constructor: "KeyMacro25", Aliases: []string{}},
	{Constructor: "KeyMacro26", Aliases: []string{}},
	{Constructor: "KeyMacro27", Aliases: []string{}},
	{Constructor: "KeyMacro28", Aliases: []string{}},
	{Constructor: "KeyMacro29", Aliases: []string{}},
	{Constructor: "KeyMacro3", Aliases: []string{}},
	{Constructor: "KeyMacro30", Aliases: []string{}},
	{Constructor: "KeyMacro4", Aliases: []string{}},
	{Constructor: "KeyMacro5", Aliases: []string{}},
	{Constructor: "KeyMacro6", Aliases: []string{}},
	{Constructor: "KeyMacro7", Aliases: []string{}},
	{Constructor: "KeyMacro8", Aliases: []string{}},
	{Constructor: "KeyMacro9", Aliases: []string{}},
	{Constructor: "KeyMacroPreset1", Aliases: []string{}},
	{Constructor: "KeyMacroPreset2", Aliases: []string{}},
	{Constructor: "KeyMacroPreset3", Aliases: []string{}},
	{Constructor: "KeyMacroPresetCycle", Aliases: []string{}},
	{Constructor: "KeyMacroRecordStart", Aliases: []string{}},
	{Constructor: "KeyMacroRecordStop", Aliases: []string{}},
	{Constructor: "KeyMail", Aliases: []string{"emailreader"}},
	{Constructor: "KeyMarkWaypoint", Aliases: []string{}},
	{Constructor: "KeyMedia", Aliases: []string{"imagebrowser"}},
	{Constructor: "KeyMediaRepeat", Aliases: []string{"repeat"}},
	{Constructor: "KeyMediaTopMenu", Aliases: []string{}},
	{Constructor: "KeyMemo", Aliases: []string{"messages"}},
	{Constructor: "KeyMenu", Aliases: []string{}},
	{Constructor: "KeyMessenger", Aliases: []string{"instantmessaging"}},
	{Constructor: "KeyMhp", Aliases: []string{}},
	{Constructor: "KeyMicmute", Aliases: []string{"micm"}},
	{Constructor: "KeyMinus", Aliases: []string{"min", "-"}},
	{Constructor: "KeyMissionCtrl", Aliases: []string{"mctl"}},
	{Constructor: "KeyMode", Aliases: []string{}},
	{Constructor: "KeyMove", Aliases: []string{}},
	{Constructor: "KeyMp3", Aliases: []string{}},
	{Constructor: "KeyMsDos", Aliases: []string{}},
	{Constructor: "KeyMuhenkan", Aliases: []string{"muh", "i5", "int5", "international5"}},
	{Constructor: "KeyMute", Aliases: []string{"mininteresting"}},
	{Constructor: "KeyN", Aliases: []string{}},
	{Constructor: "KeyNavChart", Aliases: []string{}},
	{Constructor: "KeyNavInfo", Aliases: []string{}},
	{Constructor: "KeyNew", Aliases: []string{}},
	{Constructor: "KeyNews", Aliases: []string{"newsreader"}},
	{Constructor: "KeyNextElement", Aliases: []string{}},
	{Constructor: "KeyNextFavorite", Aliases: []string{}},
	{Constructor: "KeyNextSong", Aliases: []string{"next", "nexttrack"}},
	{Constructor: "KeyNotificationCenter", Aliases: []string{}},
	{Constructor: "KeyNumLock", Aliases: []string{"nlck"}},
	{Constructor: "KeyNumeric0", Aliases: []string{}},
	{Constructor: "KeyNumeric1", Aliases: []string{}},
	{Constructor: "KeyNumeric11", Aliases: []string{}},
	{Constructor: "KeyNumeric12", Aliases: []string{}},
	{Constructor: "KeyNumeric2", Aliases: []string{}},
	{Constructor: "KeyNumeric3", Aliases: []string{}},
	{Constructor: "KeyNumeric4", Aliases: []string{}},
	{Constructor: "KeyNumeric5", Aliases: []string{}},
	{Constructor: "KeyNumeric6", Aliases: []string{}},
	{Constructor: "KeyNumeric7", Aliases: []string{}},
	{Constructor: "KeyNumeric8", Aliases: []string{}},
	{Constructor: "KeyNumeric9", Aliases: []string{}},
	{Constructor: "KeyNumericA", Aliases: []string{}},
	{Constructor: "KeyNumericB", Aliases: []string{}},
	{Constructor: "KeyNumericC", Aliases: []string{}},
	{Constructor: "KeyNumericD", Aliases: []string{}},
	{Constructor: "KeyNumericPound", Aliases: []string{}},
	{Constructor: "KeyNumericStar", Aliases: []string{}},
	{Constructor: "KeyO", Aliases: []string{}},
	{Constructor: "KeyOk", Aliases: []string{}},
	{Constructor: "KeyOnScreenKeyboard", Aliases: []string{}},
	{Constructor: "KeyOpen", Aliases: []string{"exec", "execute"}},
	{Constructor: "KeyOption", Aliases: []string{}},
	{Constructor: "KeyP", Aliases: []string{}},
	{Constructor: "KeyPageDown", Aliases: []string{"pgdn"}},
	{Constructor: "KeyPageUp", Aliases: []string{"pgup"}},
	{Constructor: "KeyPaste", Aliases: []string{}},
	{Constructor: "KeyPause", Aliases: []string{}},
	{Constructor: "KeyPauseCd", Aliases: []string{}},
	{Constructor: "KeyPauseRecord", Aliases: []string{}},
	{Constructor: "KeyPc", Aliases: []string{}},
	{Constructor: "KeyPhone", Aliases: []string{}},
	{Constructor: "KeyPickupPhone", Aliases: []string{}},
	{Constructor: "KeyPlay", Aliases: []string{}},
	{Constructor: "KeyPlayCd", Aliases: []string{}},
	{Constructor: "KeyPlayPause", Aliases: []string{"pp"}},
	{Constructor: "KeyPlayer", Aliases: []string{}},
	{Constructor: "KeyPower", Aliases: []string{}},
	{Constructor: "KeyPower2", Aliases: []string{}},
	{Constructor: "KeyPresentation", Aliases: []string{}},
	{Constructor: "KeyPreviousElement", Aliases: []string{}},
	{Constructor: "KeyPreviousSong", Aliases: []string{"prev", "previoustrack"}},
	{Constructor: "KeyPrint", Aliases: []string{"prnt"}},
	{Constructor: "KeyPrivacyScreenToggle", Aliases: []string{}},
	{Constructor: "KeyProg1", Aliases: []string{}},
	{Constructor: "KeyProg2", Aliases: []string{}},
	{Constructor: "KeyProg3", Aliases: []string{}},
	{Constructor: "KeyProg4", Aliases: []string{}},
	{Constructor: "KeyProgram", Aliases: []string{"guide"}},
	{Constructor: "KeyProps", Aliases: []string{"properties"}},
	{Constructor: "KeyPvr", Aliases: []string{}},
	{Constructor: "KeyQ", Aliases: []string{}},
	{Constructor: "KeyQuestion", Aliases: []string{}},
	{Constructor: "KeyR", Aliases: []string{}},
	{Constructor: "KeyRadarOverlay", Aliases: []string{}},
	{Constructor: "KeyRadio", Aliases: []string{}},
	{Constructor: "KeyRecord", Aliases: []string{}},
	{Constructor: "KeyRed", Aliases: []string{}},
	{Constructor: "KeyRedo", Aliases: []string{}},
	{Constructor: "KeyRefresh", Aliases: []string{}},
	{Constructor: "KeyRefreshRateToggle", Aliases: []string{}},
	{Constructor: "KeyReply", Aliases: []string{}},
	{Constructor: "KeyReserved", Aliases: []string{}},
	{Constructor: "KeyRestart", Aliases: []string{}},
	{Constructor: "KeyRewind", Aliases: []string{}},
	{Constructor: "KeyRfkill", Aliases: []string{}},
	{Constructor: "KeyRight", Aliases: []string{"rght"}},
	{Constructor: "KeyRightAlt", Aliases: []string{"ralt"}},
	{Constructor: "KeyRightBrace", Aliases: []string{"rbrc", "]"}},
	{Constructor: "KeyRightCtrl", Aliases: []string{"rctrl", "rctl"}},
	{Constructor: "KeyRightDown", Aliases: []string{}},
	{Constructor: "KeyRightMeta", Aliases: []string{"rmeta", "rmet"}},
	{Constructor: "KeyRightShift", Aliases: []string{"rshift", "rshft", "rsft"}},
	{Constructor: "KeyRightUp", Aliases: []string{}},
	{Constructor: "KeyRo", Aliases: []string{"i1", "int1", "international1"}},
	{Constructor: "KeyRootMenu", Aliases: []string{}},
	{Constructor: "KeyRotateLockToggle", Aliases: []string{}},
	{Constructor: "KeyS", Aliases: []string{}},
	{Constructor: "KeySat", Aliases: []string{}},
	{Constructor: "KeySat2", Aliases: []string{}},
	{Constructor: "KeySave", Aliases: []string{}},
	{Constructor: "KeyScale", Aliases: []string{}},
	{Constructor: "KeyScreen", Aliases: []string{"aspectratio"}},
	{Constructor: "KeyScreenSaver", Aliases: []string{}},
	{Constructor: "KeyScrollDown", Aliases: []string{"scrdn", "sdwn", "sdn"}},
	{Constructor: "KeyScrollLock", Aliases: []string{"scrlck", "slck"}},
	{Constructor: "KeyScrollUp", Aliases: []string{"scrup", "sup"}},
	{Constructor: "KeySearch", Aliases: []string{}},
	{Constructor: "KeySelect", Aliases: []string{}},
	{Constructor: "KeySelectiveScreenshot", Aliases: []string{}},
	{Constructor: "KeySemicolon", Aliases: []string{"scln", ";"}},
	{Constructor: "KeySend", Aliases: []string{}},
	{Constructor: "KeySendFile", Aliases: []string{}},
	{Constructor: "KeySetup", Aliases: []string{}},
	{Constructor: "KeyShop", Aliases: []string{}},
	{Constructor: "KeyShuffle", Aliases: []string{}},
	{Constructor: "KeySidevuSonar", Aliases: []string{}},
	{Constructor: "KeySingleRangeRadar", Aliases: []string{}},
	{Constructor: "KeySlash", Aliases: []string{"/"}},
	{Constructor: "KeySleep", Aliases: []string{"zzz"}},
	{Constructor: "KeySlow", Aliases: []string{}},
	{Constructor: "KeySlowreverse", Aliases: []string{}},
	{Constructor: "KeySos", Aliases: []string{}},
	{Constructor: "KeySound", Aliases: []string{"audiobrowser"}},
	{Constructor: "KeySpace", Aliases: []string{"spc"}},
	{Constructor: "KeySpellCheck", Aliases: []string{}},
	{Constructor: "KeySport", Aliases: []string{}},
	{Constructor: "KeySpotlight", Aliases: []string{"spot"}},
	{Constructor: "KeySpreadSheet", Aliases: []string{}},
	{Constructor: "KeyStop", Aliases: []string{}},
	{Constructor: "KeyStopCd", Aliases: []string{}},
	{Constructor: "KeyStopRecord", Aliases: []string{}},
	{Constructor: "KeySubtitle", Aliases: []string{"caption"}},
	{Constructor: "KeySuspend", Aliases: []string{}},
	{Constructor: "KeySwitchVideoMode", Aliases: []string{}},
	{Constructor: "KeySysRq", Aliases: []string{"ssrq", "sys"}},
	{Constructor: "KeyT", Aliases: []string{}},
	{Constructor: "KeyTab", Aliases: []string{}},
	{Constructor: "KeyTape", Aliases: []string{}},
	{Constructor: "KeyTaskmanager", Aliases: []string{}},
	{Constructor: "KeyTeen", Aliases: []string{}},
	{Constructor: "KeyText", Aliases: []string{}},
	{Constructor: "KeyTime", Aliases: []string{}},
	{Constructor: "KeyTitle", Aliases: []string{}},
	{Constructor: "KeyTouchpadOff", Aliases: []string{}},
	{Constructor: "KeyTouchpadOn", Aliases: []string{}},
	{Constructor: "KeyTouchpadToggle", Aliases: []string{}},
	{Constructor: "KeyTraditionalSonar", Aliases: []string{}},
	{Constructor: "KeyTuner", Aliases: []string{}},
	{Constructor: "KeyTv", Aliases: []string{}},
	{Constructor: "KeyTv2", Aliases: []string{"cable"}},
	{Constructor: "KeyTwen", Aliases: []string{}},
	{Constructor: "KeyU", Aliases: []string{}},
	{Constructor: "KeyUndo", Aliases: []string{}},
	{Constructor: "KeyUnknown", Aliases: []string{}},
	{Constructor: "KeyUnmute", Aliases: []string{}},
	{Constructor: "KeyUp", Aliases: []string{}},
	{Constructor: "KeyUwb", Aliases: []string{}},
	{Constructor: "KeyV", Aliases: []string{}},
	{Constructor: "KeyVcr", Aliases: []string{}},
	{Constructor: "KeyVcr2", Aliases: []string{"vcr+"}},
	{Constructor: "KeyVendor", Aliases: []string{}},
	{Constructor: "KeyVideo", Aliases: []string{}},
	{Constructor: "KeyVideoNext", Aliases: []string{}},
	{Constructor: "KeyVideoPhone", Aliases: []string{}},
	{Constructor: "KeyVideoPrev", Aliases: []string{}},
	{Constructor: "KeyVod", Aliases: []string{}},
	{Constructor: "KeyVoicecommand", Aliases: []string{}},
	{Constructor: "KeyVoicemail", Aliases: []string{}},
	{Constructor: "KeyVolumeDown", Aliases: []string{"voldwn", "vold", "volumedecrement"}},
	{Constructor: "KeyVolumeUp", Aliases: []string{"volu", "volumeincrement"}},
	{Constructor: "KeyW", Aliases: []string{}},
	{Constructor: "KeyWakeUp", Aliases: []string{"wkup"}},
	{Constructor: "KeyWimax", Aliases: []string{"wwan"}},
	{Constructor: "KeyWlan", Aliases: []string{}},
	{Constructor: "KeyWordProcessor", Aliases: []string{}},
	{Constructor: "KeyWpsButton", Aliases: []string{}},
	{Constructor: "KeyWww", Aliases: []string{"internetbrowser"}},
	{Constructor: "KeyX", Aliases: []string{}},
	{Constructor: "KeyXfer", Aliases: []string{}},
	{Constructor: "KeyY", Aliases: []string{}},
	{Constructor: "KeyYellow", Aliases: []string{}},
	{Constructor: "KeyYen", Aliases: []string{"i3", "int3", "international3"}},
	{Constructor: "KeyZ", Aliases: []string{}},
	{Constructor: "KeyZenkakuHankaku", Aliases: []string{"zeh", "l5", "lang5"}},
	{Constructor: "KeyZoom", Aliases: []string{"fullscreen"}},
	{Constructor: "KeyZoomIn", Aliases: []string{}},
	{Constructor: "KeyZoomOut", Aliases: []string{}},
	{Constructor: "KeyZoomReset", Aliases: []string{}},
}

// kmonadKeycodeTokens maps every accepted spelling to its Keycode constructor.
var kmonadKeycodeTokens = buildKMonadKeycodeTokens()

func buildKMonadKeycodeTokens() map[string]string {
	tokens := make(map[string]string)
	for _, keycode := range kmonadKeycodes {
		short := strings.TrimPrefix(keycode.Constructor, "Key")
		for _, token := range []string{
			keycode.Constructor, strings.ToLower(keycode.Constructor),
			short, strings.ToLower(short),
		} {
			tokens[token] = keycode.Constructor
		}
		for _, alias := range keycode.Aliases {
			tokens[alias] = keycode.Constructor
		}
	}
	return tokens
}

// KnownKMonadKeys returns the accepted keyboard-token vocabulary at the pinned
// KMonad commit. The compiler requires every defsrc token and every emitted
// single-key behavior to be one of these spellings.
func KnownKMonadKeys() map[string]bool {
	keys := make(map[string]bool, len(kmonadKeycodeTokens))
	for token := range kmonadKeycodeTokens {
		keys[token] = true
	}
	return keys
}
